services:
  backend:
    build: ./sensor_api
    ports:
      - "3004:3004"
    volumes:
      - ./sensor_api:/app

  frontend:
    build: ./sensor-frontend
    ports:
      - "3333:3333"
    volumes:
      - ./sensor-frontend:/app
    environment:
      - VUE_APP_BACKEND_URL=http://backend:3004/api/
